The function Transformer takes as input a single function that will be applied to each sample in the data.this function can be any Python function that a single argument, such as a lambda function or a user-defined function. The function should return the transformed sample.

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset

X_transform = FunctionTransformer(np.log1p)


In [ ]:
#Custom Feature Engineering

from sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1,2],[3,4]])

# define a custom feature Engineering function
def holi(X):
  return np.hstack((X,X**2))

#Create a functionTransformer to apply the custom data
custom_transformer = FunctionTransformer(holi)

#Apply the transformer to the input data
X_transformed= custom_transformer.transform(X)

#view the tranformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset
x=np.array([[1,2],[3,4]])

# define  a custom scalling function
def my_scalling(x):
  return x/np.max(x)

# custom a Function Transformer to apply the custom function
custom_transformer=FunctionTransformer(my_scalling)

x_transformed=custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
## Data Cleaning..

from sklearn.preprocessing import FunctionTransformer
import numpy as np

x=np.array([[1,2],[3,np.nan]])

def my_cleaning(x):
  x[np.isnan(x)]=0
  return x

custom_transformer=FunctionTransformer(my_cleaning)

x_transformed=custom_transformer.transform(x)

print(x_transformed)


[[1. 2.]
 [3. 0.]]


In [ ]:
## FUNCTION TRANSFORMER APPLY ON DATASET


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/placement - placement.csv')

In [ ]:
df.head(4)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [ ]:
x=df.drop(columns=['placed'])
y=df['placed']

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform=FunctionTransformer(np.log1p)
x_transformed=log_transform.fit_transform(x)
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')

In [ ]:
df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [ ]:
x=np.array([[df]])

def separate_columns(df):
    int_columns = [col
                   for col in df.columns
                   if df[col].dtype == 'int64']

    float_columns = [col
                     for col in df.columns
                     if df[col].dtype == 'float64']

    object_columns = [col
                      for col in df.columns
                      if df[col].dtype == 'object']

    return int_columns, float_columns, object_columns

int_cols, float_cols, object_cols=separate_columns(df)

print("Integer columns:", int_cols)
print("Float columns:", float_cols)
print("Object columns:", object_cols)



# df.isnull().sum()



Integer columns: ['age']
Float columns: ['fever']
Object columns: ['gender', 'cough', 'city', 'has_covid']


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['cough']=le.fit_transform(df['cough'])
df['city']=le.fit_transform(df['city'])
df['gender']=le.fit_transform(df['gender'])
df['has_covid']=le.fit_transform(df['has_covid'])

df.head(3)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0